export enum GratitudeMyListTypes {
  GRATITUDE_MY_LIST_LOAD = 'GRATITUDE_MY_LIST_LOAD',
  GRATITUDE_MY_LIST_RELOAD = 'GRATITUDE_MY_LIST_RELOAD',
  GRATITUDE_MY_LIST_ITEM_ADD = 'GRATITUDE_MY_ITEM_ADD',
  GRATITUDE_MY_LIST_ITEM_UPDATE = 'GRATITUDE_MY_LIST_ITEM_UPDATE',
  GRATITUDE_MY_LIST_ITEM_REMOVE = 'GRATITUDE_MY_LIST_ITEM_REMOVE',
  GRATITUDE_MY_LIST_SET_FILTERS = 'GRATITUDE_MY_LIST_SET_FILTERS'
}
