export enum UserGratitudeListTypes {
  USER_GRATITUDE_LIST_LOAD = 'USER_GRATITUDE_LIST_LOAD',
  USER_GRATITUDE_LIST_RELOAD = 'USER_GRATITUDE_LIST_RELOAD',
  USER_GRATITUDE_LIST_ITEM_UPDATE = 'USER_GRATITUDE_LIST_ITEM_UPDATE',
  USER_GRATITUDE_LIST_ITEM_REMOVE = 'USER_GRATITUDE_LIST_ITEM_REMOVE',
  USER_GRATITUDE_LIST_SET_FILTERS = 'USER_GRATITUDE_LIST_SET_FILTERS'
}
