export enum UserFriendFollowingTypes {
  USER_FRIEND_FOLLOWING_LOAD = 'USER_FRIEND_FOLLOWING_LOAD',
  USER_FRIEND_FOLLOWING_RELOAD = 'USER_FRIEND_FOLLOWING_RELOAD',
  USER_FRIEND_FOLLOWING_ITEM_REMOVE = 'USER_FRIEND_FOLLOWING_ITEM_REMOVE'
}
