export enum UserFriendFollowerTypes {
  USER_FRIEND_FOLLOWER_LOAD = 'USER_FRIEND_FOLLOWER_LOAD',
  USER_FRIEND_FOLLOWER_RELOAD = 'USER_FRIEND_FOLLOWER_RELOAD',
  USER_FRIEND_FOLLOWER_ITEM_REMOVE = 'USER_FRIEND_FOLLOWER_ITEM_REMOVE'
}
