export const Paths = {
  Home: '/',
  Support: '/support',
  AccessDenied: '/access-denied',
  PageNotFound: '/page-not-found',
  Gratitude: '/gratitude',
  Habit: '/habits',
  HabitTracker: '/habits/tracker',
  HabitArchive: '/habits/archive',
  HabitView: '/habits/:id',
  Friend: '/friends',
  FriendFollowing: '/friends/following',
  FriendFollowers: '/friends/followers',
  UserView: '/user/:id',
};
