export const Paths = {
  Home: '/',
  Support: '/support',
  AccessDenied: '/access-denied',
  PageNotFound: '/page-not-found',
  Gratitude: '/gratitude',
  Habit: '/habits',
  HabitTracker: '/habits/tracker',
  HabitArchive: '/habits/archive',
  HabitView: '/habits/:id',
  Friend: '/friends',
  FriendFollowing: '/friends/following',
  FriendFollowers: '/friends/followers',
  UserView: '/user/:id',
  UserViewHabit: '/user/:id/habits',
  UserViewHabitView: '/user/:id/habits/:habitId',
  UserViewGratitude: '/user/:id/gratitude',
  UserViewFollowing: '/user/:id/following',
  UserViewFollowers: '/user/:id/followers'
};
