export enum FriendFollowingTypes {
  FRIEND_FOLLOWING_LOAD = 'FRIEND_FOLLOWING_LOAD',
  FRIEND_FOLLOWING_RELOAD = 'FRIEND_FOLLOWING_RELOAD',
  FRIEND_FOLLOWING_ITEM_REMOVE = 'FRIEND_FOLLOWING_ITEM_REMOVE'
}
