export enum FriendFollowerTypes {
  FRIEND_FOLLOWER_LOAD = 'FRIEND_FOLLOWER_LOAD',
  FRIEND_FOLLOWER_RELOAD = 'FRIEND_FOLLOWER_RELOAD',
  FRIEND_FOLLOWER_ITEM_REMOVE = 'FRIEND_FOLLOWER_ITEM_REMOVE'
}
